# Examples of applying file data utilities

In [1]:
using GridUtilities

┌ Info: Precompiling GridUtilities [5c019650-0847-4ff6-8f91-f8ecfc8c3009]
└ @ Base loading.jl:1260


### Example data sampling

Here, we will sample and store data from a simple update model

In [25]:
u0 = ones(5,5)
t = 0.0
u = deepcopy(u0);

Now we set up a `StorePlan` to provide details on what we wish to store and how often. We can assign names to each variable.

In [26]:
t_sample = 0.05

S = StorePlan(t_sample,"state" => u0, "time" => t)

data_history = initialize_storage(S)

Dict{String,History} with 2 entries:
  "time"  => Float64[]
  "state" => Array{Float64,2}[]

In [27]:
store_data!(data_history,t,S,"state"=>deepcopy(u),"time"=>t)

for i in 1:100
    u .+= u0 # simple model, just for making it dynamic
    t += 0.01
    store_data!(data_history,t,S,"state"=>u,"time"=>t)
end

Let's see how we can look at the sampled data

In [35]:
data_history["state"][1]

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [36]:
data_history["time"][1]

0.0

It is easy to save the data to file

In [44]:
save("stuff.jld","data",data_history)

and load it back in

In [46]:
d = load("stuff.jld")

Dict{String,Any} with 1 entry:
  "data" => Dict{String,History}("time"=>[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3,…

In [53]:
d["data"]["state"][5]

5×5 Array{Float64,2}:
 21.0  21.0  21.0  21.0  21.0
 21.0  21.0  21.0  21.0  21.0
 21.0  21.0  21.0  21.0  21.0
 21.0  21.0  21.0  21.0  21.0
 21.0  21.0  21.0  21.0  21.0

In [54]:
d["data"]["time"][5]

0.20000000000000004

### Writing data to file

In [71]:
u0 = ones(5,5)
t = 0.0
u = deepcopy(u0);

In [72]:
filen = "storeddata.jld"
restart_Δt = 0.1
R = WritePlan(filen,restart_Δt,"state" => u,"t" => t)

WritePlan("storeddata.jld", 0.1, Dict{String,Type}("t" => Float64,"state" => Array{Float64,2}))

In [73]:
for i in 1:100
    u .+= u0 # simple model, just for making it dynamic
    t += 0.01
    save(t,R,"state" => u,"t" => t)
end

We can restart this by loading from the file

In [74]:
restart = load(R)
u = restart["state"]
t = restart["t"]

1.0000000000000007

and keep running

In [75]:
for i in 1:100
    u .+= u0 # simple model, just for making it dynamic
    t += 0.01
    save(t,R,"state" => u,"t" => t)
end

In [76]:
t

2.0000000000000013

In [77]:
u

5×5 Array{Float64,2}:
 201.0  201.0  201.0  201.0  201.0
 201.0  201.0  201.0  201.0  201.0
 201.0  201.0  201.0  201.0  201.0
 201.0  201.0  201.0  201.0  201.0
 201.0  201.0  201.0  201.0  201.0